### PR TITLE
Jungle tweaks

### PR DESCRIPTION
**Pull request by reaperrr**
Tweaks palettes for less blueish terrain, RA version crash-fix (v04.jun incompatible with sequences).
jungle-green
jungle-td-green

### CODE REVIEW

**Comment by Mailaender** [comment]
Is it safe to just remove `v04`? https://github.com/OpenRA/OpenRA/blob/bleed/mods/ra/sequences/decorations.yaml#L256

**Comment by Mailaender** [comment]
Turns out it is (tested against Artemis).

**Comment by reaperrr** [comment]
It should be, the mod just backfalls to v04.tem then, which has the correct sequences.

**Comment by Mailaender** [comment]
Do we lose artwork here or was it just a duplicate anyway?

**Comment by reaperrr** [comment]
Hm, I checked and actually, we do lose artwork. RA v04 has some (seemingly unused) active sequences defined, the damaged one calls for a fourth frame which doesn't exist for the jungle version, hence why it crashed. Since the normal damaged frame of both artworks doesn't match either (for v04.tem it's the 3rd frame, for the original v04.jun it's the 2nd), I'll submit a modified v04.jun.

**Pull request merged**
